name: "Project Build"

on:
  pull_request:
    branches: [master, develop]
  push:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        version : [19]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          version: ${{ matrix.version }}

      - name: Try to build the project
        run: docker build -t project .;
